[package]
name = "santui-totp-viewer"
version = "0.2.40"
edition = "2024"
rust-version = "1.85"

[[bin]]
name = "santui-totp-viewer"
path = "src/main.rs"

[dependencies]
santui-ipc = { path = "../../ipc", version = "0.2.40", default-features = false, features = ["clipboard"] }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
sha1 = "0.11"
