[package]
name = "santui-bmi-calculator"
version = "0.2.38"
edition = "2024"
rust-version = "1.85"

[[bin]]
name = "santui-bmi-calculator"
path = "src/main.rs"

[dependencies]
santui-ipc = { path = "../../ipc", version = "0.2.38", default-features = false, features = ["clipboard"] }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
