[package]
name = "santui-jwt-inspector"
version = "0.2.36"
edition = "2021"

[[bin]]
name = "santui-jwt-inspector"
path = "src/main.rs"

[dependencies]
santui-ipc = { path = "../../ipc", version = "0.2.36", default-features = false, features = ["clipboard"] }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
base64 = "0.22"
