[package]
name = "santui-radio-stream-scraper"
version = "0.2.39"
edition = "2024"
rust-version = "1.85"

[dependencies]
ureq = "3"
serde = { workspace = true }
serde_json = { workspace = true }
rusqlite = { version = "0.40", features = ["bundled"] }
log = { workspace = true }
env_logger = { workspace = true }
