[package]
name = "santui-bookmark-launcher"
version = "0.2.35"
edition = "2021"

[[bin]]
name = "santui-bookmark-launcher"
path = "src/main.rs"

[dependencies]
santui-ipc = { path = "../../ipc", version = "0.2.35", default-features = false, features = ["clipboard", "time"] }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
